# Playbook to upgrade Python on ubuntu from 2.7 to 3.6

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: add ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
        update_cache: true
        state: present

    - name: Update apt and install ansible
      apt: update_cache=yes name=ansible state=latest