# -*- mode: ruby -*-
# vi: set ft=ruby :

BOXFILE = "ubuntu/focal64"


Vagrant.configure("2") do |config|

  config.vm.define "docker" do |docker|
    docker.vm.box = "#{BOXFILE}"
    docker.vm.hostname = "devops"
    docker.vm.provision "shell", path: "../scripts/install_docker.sh"
  end 
  
    config.vm.define "node" do |node|
      node.vm.box = "#{BOXFILE}"
      node.vm.hostname = "devops"
      node.vm.provision "shell", path: "../scripts/install_node.sh"
  end
    
    config.vm.define "python" do |python|
      python.vm.box = "#{BOXFILE}"
      python.vm.hostname = "devops"
      python.vm.provision "shell", path: "../scripts/install_python.sh"
  end
      
    config.vm.define "go" do |go|
      go.vm.box = "#{BOXFILE}"
      go.vm.hostname = "devops"
      go.vm.provision "shell", path: "../scripts/install_go.sh"
  end  
    
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.box = "#{BOXFILE}"
      jenkins.vm.hostname = "jenkins-dev"
      jenkins.vm.provision "shell", path: "../scripts/installjenkins.sh"
      jenkins.vm.network "forwarded_port", guest: 8080, host: 9090, id: "jenkins"
  end
end  