# -*- mode: ruby -*-
# vi: set ft=ruby :

 # add host updater
 if Vagrant.has_plugin? 'vagrant-hostsupdater'
  config.hostsupdater.aliases = aliases
else
  puts 'vagrant-hostsupdater missing, please install the plugin:'
  puts 'vagrant plugin install vagrant-hostsupdater'
end
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]      
end
    
config.vm.define "eks" do |eks|
  eks.vm.box = "peru/ubuntu-18.04-server-amd64"
  eks.vm.hostname = "eks"
  eks.vm.network "forwarded_port", guest: 5601, host: 6601, id: "eks"
  eks.vm.provision :ansible do |ansible|
    ansible.playbook = "../playbooks/elk_stack/site.yml"
  end
end

config.vm.define "beat" do |beat|
  beat.vm.box = "peru/ubuntu-18.04-server-amd64"
  beat.vm.hostname = "beat"
  beat.vm.provision :ansible do |ansible|
    ansible.playbook = "../playbooks/elk_stack/site.yml"
  end
end

config.vm.define "elk" do |elk|
    elk.vm.box = "peru/ubuntu-18.04-server-amd64"
    elk.vm.hostname = "elk"
    elk.vm.provision :ansible do |ansible|
      ansible.playbook = "../playbooks/elk_stack/site.yml"
    end
  end
end  