
# create ubuntu server and install elk stack via playbook uses port 6601 for kibana dashboard
my_box_image = "ubuntu/bionic64"
buildelk_count = 1
my_mem_size = 4096
my_cpu_count = 2

(1..buildelk_count).each do |i|
Vagrant.configure("2") do |config|

config.vm.define "buildelk#{i}" do |buildelk|
config.vm.provider "virtualbox" do |v|
  v.memory = my_mem_size
  v.cpus = my_cpu_count
buildelk.vm.box = my_box_image
buildelk.vm.hostname = "elkserver-#{i}"
buildelk.vm.network "forwarded_port", guest: 5601, host: 6601, id: "buildelk#{i}"
buildelk.vm.provision :ansible do |ansible|
  ansible.playbook = "../playbooks/elk_stack/site.yml"
        end
      end
    end
  end
end
