
# create 3 ubuntu servers and install elk stack via playbook
my_box_image = "ubuntu/bionic64"
buildelk_count = 1
my_mem_size = 4096
my_cpu_count = 2

(1..buildelk_count).each do |i|
Vagrant.configure("2") do |config|

config.vm.define "buildelk#{i}" do |buildelk|
config.vm.provider "virtualbox" do |v|
  v.memory = 4096
  v.cpus = 2
buildelk.vm.box = my_box_image
buildelk.vm.hostname = "buildelk-#{i}"
buildelk.vm.network "public_network", bridge: ["wlp3s0"]
buildelk.vm.provision :ansible do |ansible|
  ansible.playbook = "ansible-elk-playbook/site.yml"
        end
      end
    end
  end
end