# -*- mode: ruby -*-
# vi: set ft=ruby :

 # add host updater
 if Vagrant.has_plugin? 'vagrant-hostsupdater'
    config.hostsupdater.aliases = aliases
  else
    puts 'vagrant-hostsupdater missing, please install the plugin:'
    puts 'vagrant plugin install vagrant-hostsupdater'
  end

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/bionic64"
    jenkins.vm.hostname = "jenkins-dev"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 9090, id: "jenkins"
      if Vagrant::Util::Platform.windows?
        puts 'must be windows'
    else
        puts 'its linux running ansible'
    jenkins.vm.provision :ansible do |ansible|
    ansible.playbook = "../playbooks/install_jenkins/site.yml"
            end
        end
    end
end