 Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]      
end

config.vm.define "docker" do |docker|
  docker.vm.box = "peru/ubuntu-18.04-server-amd64"
  docker.vm.hostname = "docker"
  docker.vm.provision "shell", path: "../scripts/docker.sh"
  end
end
