
---
#
# Playbook to install the ELK stack + metric beat
#
- hosts: buildelk1
  remote_user: vagrant
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: metricbeat }