Vagrant.configure("2") do |config|

  ## 2 ubuntu 18.04 LTS VMs 
  (10..11).each do |i|
    config.vm.define "ubuntu#{i}" do | ubuntu |
      ubuntu.vm.box = "ubuntu/bionic64"
      ubuntu.vm.network "private_network", ip: "192.168.50.#{i}"
      ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
    
    end
  end 

  ## 2 centos 8 VMs
  (20..21).each do |i|
    config.vm.define "centos#{i}" do | centos |
      centos.vm.box = "centos/8"
      centos.vm.network "private_network", ip: "192.168.50.#{i}"
    end
  end

## 2 centos 7 VMs
 (20..21).each do |i|
    config.vm.define "centos#{i}" do | centos |
      centos.vm.box = "centos/7"
      centos.vm.network "private_network", ip: "192.168.50.#{i}"
    end
  end


config.vm.box_check_update = false
config.vm.provider "virtualbox" do |v|
config.vm.provision "ansible" do |ansible|
ansible.playbook = "playbooks/upgrade_python/playbook.yml"

    # add vboxmanage customizations here:
    # https://www.vagrantup.com/docs/virtualbox/configuration.html
    # "convenience shortcuts for memory and CPU settings:" (per link above), tweak to your machine's capabilities to speed up VMs:
      v.memory = 1024
      v.cpus = 1

        end
    end
end 
