Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.hostname = "host-win"
  winClientIP = "192.168.99.103"
  config.vm.network "private_network", ip: winClientIP
end