
Vagrant.configure("2") do |config|
  config.vm.define "hello" do
    config.vm.provider "docker" do |d|
      d.image = "hello-world"
      d.remains_running = false
       end
  end


config.vm.define "ngnix" do
    config.vm.provider "docker" do |d|
      d.image = "nginix"
      d.remains_running = true
    end
  end
end