- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  # Install cloud tools for dev work
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  # Setup Python 
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['python3-pip', 'virtualenv', 'python3-setuptools', 'python3.8']

    - name: Installing AWS Cli
      pip:
         name: awscli
         version: 1.18.41
    
    - name: Installing Azure Cli
      pip:
         name: azure-cli
         version: 2.0.43
    