Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]      
end

config.vm.define "chefserver" do |chefserver|
  chefserver.vm.box = "peru/ubuntu-18.04-server-amd64"
  chefserver.vm.hostname = "chefserver"
  chefserver.vm.network "forwarded_port", guest: 443, host: 9443, id: "chefserver"
  chefserver.vm.network "forwarded_port", guest: 80, host: 8080, id: "chefserver"
  chefserver.vm.provision "shell", path: "../scripts/install_chef_standalone_server.sh"
  end
end
