# Playbook to upgrade Python on ubuntu from 2.7 to 3.6
- name: Upgrade Python on Ubuntu
  gather_facts: true
  hosts: ubuntu10
  become: true
  tags: installpython
  tasks:  
  
  # Add Python PPA 
  - apt_repository:
     repo: ppa:deadsnakes/ppa
     update_cache: true
  
  # Update Python Packages
  - apt:
     pkg:
       - software-properties-common
       - python3.8
       - python3-pip
     state: latest
  - alternatives:
      link: /usr/bin/python
      name: python
      path: /usr/bin/python3