 
---
#
# Installing Java 8

- name: APT Update
  command: apt update
    
- name: Install prereq
  command: apt install curl gnupg-agent software-properties-common gnupg -y

- name: Add the Java PPA repo
  apt_repository: 
   repo: ppa:webupd8team/java

# Accept Oracle license

- name: Automatically accept the Oracle license 
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  
# Install Java 

- name: Install Java 8
  apt:
   name:  openjdk-8-jre-headless, default-jdk
   state: present
   update_cache: yes
